### PR TITLE
Changes to UI/costs/benefits

### PR DESCRIPTION
**Pull request by rsa-ingo**
... as mentioned on LinkedIn...

### CODE REVIEW

**Comment by EthanHeilman** [comment]
This is awesome! Thanks for doing this.

It has so many dependencies, 2000+ files added, anyway we can slim this down and can check these into git. Maybe use a github action to install the dependencies when pushing to github pages? What tooling are you using to manage these dependencies?

**Comment by rsa-ingo** [comment]
My thinking was that this should work offline. However.... that means the PR has a ton of changes/files.

OK, let me re-do this. I'll make changes so the GUI libs are simply linked in from a CDN and make another PR.

I will keep a version running completely offline in my repository. That should make everyone happy.... right?

**Comment by EthanHeilman** [comment]
@rsa-ingo I wonder if you could still support offline but without all the unused files. Something like a asset packer or asset pipeline. I think most of these 2000 files are unused.

When I load it over the web, it only downloads 14 files
image

**Comment by rsa-ingo** [comment]
Well, let me tell you a dark secret of mine: I write code to get things working and then this is basically it. 
Lucky for me, my code (almost!) never makes it into production. Hence when it comes to all the important bits of software development, I'm really into making this somebody else's problem. 

This includes proper packaging. :-D

**Comment by EthanHeilman** [comment]
>  I write code to get things working and then this is basically it.

That's fair and reflects the approach I took with flipIt.  I think I'll try to fix this up next week but PR #2 seems like a better more immediate solution.

**Pull request merged**
